(()=>{
const URL='https://wfxuxrvygyzonkflpwoq.supabase.co',KEY='sb_publishable_e2h4t8AvCobzftt36UrDbw_NJGq8qlJ';
const db=supabase.createClient(URL,KEY),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const empty=(message,tag='div')=>`<${tag} class="live-empty">${esc(message)}</${tag}>`;
function applyContent(rows){const c=Object.fromEntries((rows||[]).map(x=>[x.key,x.value]));if(c.phone){document.querySelectorAll('a[href^="tel:"]').forEach(a=>{a.href=`tel:${c.phone.replace(/[^+\d]/g,'')}`;if(/Call/.test(a.textContent))a.innerHTML=`<i class="fa-solid fa-phone"></i> Call ${esc(c.phone)}`})}if(c.email)document.querySelectorAll('a[href^="mailto:"]').forEach(a=>{a.href=`mailto:${c.email}`;a.lastChild.textContent=c.email});if(c.business)document.title=c.business;if(c.website_headline)document.querySelector('.hero h1').textContent=c.website_headline;if(c.website_subtitle)document.querySelector('.hero .lead').textContent=c.website_subtitle;const facts=document.querySelectorAll('.facts .fact span:last-child');if(c.open&&c.close&&facts[1])facts[1].innerHTML=`Monday–Saturday<br>${esc(c.open)}–${esc(c.close)}`;if(c.area&&facts[2])facts[2].textContent=c.area;if(c.email&&facts[3])facts[3].textContent=c.email;const services=document.querySelector('#services'),reviews=document.querySelector('#reviews-live');if(services)services.hidden=c.show_services==='false';if(reviews)reviews.hidden=c.show_reviews==='false'}
function renderServices(rows){const grid=document.querySelector('#services .service-grid');if(!grid)return;grid.innerHTML=rows?.length?rows.map((s,i)=>`<article class="service-card"><div class="service-copy"><span class="service-icon">${esc(s.icon||'✦')}</span><h3>${esc(s.name)}</h3><p>${esc(s.description||'')}</p><a class="card-arrow open-estimate" href="#estimate" data-live-service="${esc(s.name)}" aria-label="Request ${esc(s.name)} estimate"><i class="fa-solid fa-arrow-right"></i></a></div></article>`).join(''):empty('Services will appear here when published.');const select=document.querySelector('#service');if(select)select.innerHTML='<option value="">Choose a service</option>'+rows.map(s=>`<option>${esc(s.name)}</option>`).join('');grid.querySelectorAll('[data-live-service]').forEach(a=>a.onclick=e=>{e.preventDefault();select.value=a.dataset.liveService;document.querySelector('#estimate')?.showModal()})}
function renderReviews(rows){let section=document.querySelector('#reviews-live');if(!section){section=document.createElement('section');section.id='reviews-live';section.className='live-reviews';document.querySelector('#contact')?.before(section)}section.innerHTML=`<div class="wrap"><div class="section-head"><div class="eyebrow">Customer feedback</div><h2>Reviews</h2></div><div class="live-review-grid">${rows?.length?rows.map(r=>`<article class="live-review"><div class="stars">${'★'.repeat(r.rating)}</div><p>${esc(r.body)}</p><strong>${esc(r.author)}</strong></article>`).join(''):empty('Published reviews will appear here.')}</div></div>`}
async function load(){const [services,reviews,content]=await Promise.all([db.from('sheylaspro-services').select('*').eq('is_live',true).order('sort_order'),db.from('sheylaspro-reviews').select('*').eq('published',true).order('created_at',{ascending:false}),db.from('sheylaspro-site_content').select('*')]);if(services.error)renderServices([]);else renderServices(services.data);if(reviews.error)renderReviews([]);else renderReviews(reviews.data);if(!content.error)applyContent(content.data);const error=services.error||reviews.error||content.error;document.documentElement.dataset.supabase=error?'error':'connected';if(error)console.error('Sheylas Pro Supabase connection:',error.message)}
const form=document.querySelector('#estimate-form');if(form)form.addEventListener('submit',async e=>{e.preventDefault();e.stopImmediatePropagation();const f=form.elements,status=document.querySelector('#status'),payload={client_name:f.name.value.trim(),phone:f.phone.value.trim(),service:f.service.value,details:f.details.value.trim(),request_type:f.requestType.value,status:'new'};status.textContent='Sending request…';const {error}=await db.from('sheylaspro-estimates').insert(payload);if(error){status.textContent=`Could not send request: ${error.message}`;return}status.textContent='Your request was sent successfully.';form.reset();setTimeout(()=>document.querySelector('#estimate')?.close(),900)},true);
document.head.insertAdjacentHTML('beforeend','<style>.live-empty{grid-column:1/-1;padding:32px;text-align:center}.live-reviews{padding:80px 0;background:#fff}.live-review-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:18px}.live-review{padding:24px;border-radius:20px;background:#f7f1ff}.live-review .stars{color:#f2b800}.live-review p{line-height:1.65}@media(max-width:760px){.live-review-grid{grid-template-columns:1fr}}</style>');load();
db.channel('sheylaspro-public').on('postgres_changes',{event:'*',schema:'public',table:'sheylaspro-services'},load).on('postgres_changes',{event:'*',schema:'public',table:'sheylaspro-reviews'},load).on('postgres_changes',{event:'*',schema:'public',table:'sheylaspro-site_content'},load).subscribe();
})();
